---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app-secret
  namespace: devcontainer
spec:
  encryptedData:
    MULTICA_TOKEN: AgB86Cag/M04DsZWjIxx71vDYecc2j6zj3Qmno4FCO4r1L92eFvjdvwoJjaxR2Bwz4+WSEumjRmK37JwsZr1+Ml41rngK1pM1h48tZwXJFw8xfNaPsofmg67El+9hTxETvF/f+Z4xRLpP9FBDe227yrmhtfdRmRZDisRe1sOMpyvBc/x3sOSfdfT0YivDTgR5nIxV8uSo5sjUpHg+NqzUHX6ZiOUdFkrI+JJwC75NLqqYumB4A5MzBV7O2Jh6jMU0dc3F7E2guFuMf8+FzoWMS5QYTpUA0csX5hzEJk6UKy7yUH2/aONbw2qDxNQZugNSC1JfdQt7E6s/nyRsflNrGlhJfJZIEOfuYJkKGsX0KqPzswj/ePStKQF4iyjhut3/bIiCzXq/s1401n+QCvIkus770CBeR+Dmim6uYa2lFCt7OPhh6n2/AU3DQS67MhOq016PEiS8pEpqjH58XhGM03/db4eQyghXQk7Ma85D2X93AP7PLJZct7Z4r++vvCW1MwgPDzPgrG6w16JHbAdL4Bmz2ck5pE/Z2VBk+nmOm2ekdn0kR2MG/vMPMrKrbL7oMZ4khFD3m0gQPKH4Ek7u434tX5ZxskkwZmqIoO/3a9b3udbdcvXIVzx6BDJ25zZsmLXrkVukJj1SzYvJMuyVRjc+hmvIFQXpGNeyDbUGBbGFt44yF47NT1vBwgGy4h+PNjnSwM5S58Oa8d5KWzs6pDoSG073IL7RSObZUGySGDYBY/7t3n1coUcVDgMYQ==
    OPENCODE_SERVER_PASSWORD: AgAxIB3RJiL8j0sgkUqU749Tt2DstUaMcfr2t4oddtSTacPlH2bEyyWl5gf76Rg0ob7jxX211dHpYH67b4Bv3mMJV0DwH+Mi3/WUdzOEYqwYqsqWsIGyOrSQI39yLotOr0kRaDk2ILcm7gy1ib5pRwIg9A0ucM5TIAsO4TQ/prsvp1vSYsc6u6IfWbX1swpVC1B4bFmkrTRCcvy1ta7t/WXftKFFQSgHci2aUBv1aC8cnOZ1wptJ4FB7b2L7NIuEIChqiBPNT6dB46tbx4SOQRntV/9dZf5j3D0PU8N+HgO9TwYKZRZ97GtgrGSbatL4mdZg051SYSVVoZGIso3vsUij8UjZDqt5mmgVIi2v/Il9CHVis5j16s6tnIuIRIcjlglVcaJZUr5HNz2uJyWeUFppy0hyntY1nXI6BoUVUC1lhI1k8fR8jwcLY2SM2EIXv5D107/ZOTkg2t3To1jDPuO/zMEHeOadYmKJ3sbnwIbEFiKReIhgvM/Gs8N0W3gzMJCDDuMgDsN10aMmDpx0253joOsWlHO8edEBxG9Ee3sI8ZwEUOfA0Wt8ZdZzYbf6M6uAnRANsnkVByLDhjnkHkqznBvCNkdA0RnHfBbTkN41Rnu068QH618CIP1k6ZTbkMKEsxdIIm2MGwUC6MYFT6YgPNbNuWfAUxth6SEWwooJ81IqUk27YmIYsP0c9Z4XM8El1pKdAM6RJHsmZB3uPTnQGzaxOAo1nadmKy/e
  template:
    metadata:
      creationTimestamp: null
      name: app-secret
      namespace: devcontainer
    type: Opaque
