---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app-secret
  namespace: devcontainer
spec:
  encryptedData:
    OPENCODE_SERVER_PASSWORD: AgAPvWCar233OADJJSaLhYVMrCGO6IAax74RZrW29ni62PsMr3l8JSF6iM2d8ZdTIXYDi8dpDN0nmuxbd+PPo0WOnJmUlTvO6+zVDyiHK+MKbfC4Qz6H1ThcOcQFmpiJ7cSOZ9y3/PxDOs8EMkcII8T5QlUE8HRtdn7qTvG791zI23CbsGnu69QLZWU0oiFIwN6pBY2e24j/X6+1WBZ9DWNxq2ZwhZrcnpOa3ET/WvPrSZWOH8i+EcPpDzym7aUL0cLv2xwxW23rRKqeEypI7pY2Ra7uVRvWoW5BIaVIoAi4eVVc4HCqaY5FdJ80a56rWKKJZwq1lLRLjWQ+1XHhY26hDxp3F7cjKAx7Dp0CT7QYhqsty152TJta18Mmin22+hnFbkpewmjJAxXU3taAgBy7TIwIxtWce4j3f81BXgEOneDKFUh0kqPXHd05I2C+VEuSa9fTq2hijBphr05OUD7RyWt90rO86lfzBeosH60scbMJmXW95DwXDy4s53j0ArFaMgSxdG1rOkSs5h+/GlTAHRgYeOcxV+s06tz7neBu8B5FOFjYsNEgZLZSjDNCZur4LcVPjqumzvAWggTI6Jzoju+SZbwKNp8lSuKINb4UMFntX3UDqbJkOWY8guxrG1mqeISfLs9hOtA3aDa1M69ERA13wZGLvK89/pdRBVvRSZzncXJi0bfjeFLefkXwSgfzMrPcBlExqoWaxBVrs6i/15M+k7ol1uurLvp7
  template:
    metadata:
      creationTimestamp: null
      name: app-secret
      namespace: devcontainer
    type: Opaque
