apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
data:
  TZ: Asia/Shanghai
  OPENCODE_HOST: "0.0.0.0"
  OPENCODE_PORT: "4096"
  OPENCODE_SERVER_USERNAME: opencode
  DOCKER_HOST: tcp://localhost:2375
  DOMAIN: devcontainer.hdgcs.com
